let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("rVS7bhwxDPyVxQHpCFmkRIlqXbiIbcCJEaQwXJzPWyz8WMN7lxj+nfxJvizUvrV1Klu8WXE4M9Td3e7qdGg/94/1DnbOoP2if//+QfTAiQwHPVrDY5kjmZRLYYWMkCiYFPWIhqYyeGSDlIu0gClfyyYmPdJQI/AJTaLdPdztbn83n5/1c1ddHR/1VzZ2+tIyeJuUSUmIorGcm6ygqFAvAxSXMiB74/vOKzApWOIE5hksQsZhT+r68Ks5NnVXnVVf94f2octXzFCRCBxUAOmZLQLEqAI4PfgZm6zXi9m4QVbiSQIKZAj1kGZmyTsQRhOxxzo7YcVh9iUz+7l/fqrfu+rHZe/e9GlMEdAqRSnaICS1NObeaGew9gCK3oRSLgFW4+JGW5EEKYhJAzhONzOwXuEHVt9Oe2VVdkG2gMGpPIV/ka2RMSQLVGdMzni/8Y9JG7uN2RwgiRgZCK1GVUXdwOfyprp93R+eNFXNS3Osy2S5GHT+cVRbJAAHo1btPJIqK9qniEsAVHDIg7hlZh8YJOCQrcUddJA0GsI9uYv2o6vOm+5wao5DsCYcsYdo2RBtiFF0hl2/hTM2eAiqWQgFr9zJGm9LL9RtCJK3sghyULL9NmVa56f3Y/vaVRdt+zgu48ohHcxiGAZemEneKyl4YcR+vaTkRZBfEkebjER9Sjhtefl+m3W9Mq/v7UPz2mVmZ9VN/dY11fX+o8gJOQ8O47yPYyJYxmdnMZN0wzjFKcwT0oH1fnzPVqIxAypYtqK5mEwaRFNCb/X7/qXpO09f5v/+U4HKwv39Pw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Manufacturer = _t, #"Growth Scale 1" = _t, #"Trigger Point 1" = _t, #"Rebate 1" = _t, #"Profit 1" = _t, #"Growth Scale 2" = _t, #"Trigger Point 2" = _t, #"Rebate 2" = _t, #"Profit 2" = _t, #"Growth Scale 3" = _t, #"Trigger Point 3" = _t, #"Rebate 3" = _t, #"Profit 3" = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Manufacturer", type text}, {"Growth Scale 1", Percentage.Type}, {"Trigger Point 1", Currency.Type}, {"Rebate 1", Percentage.Type}, {"Profit 1", Currency.Type}, {"Growth Scale 2", Percentage.Type}, {"Trigger Point 2", Currency.Type}, {"Rebate 2", Percentage.Type}, {"Profit 2", Currency.Type}, {"Growth Scale 3", Percentage.Type}, {"Trigger Point 3", Currency.Type}, {"Rebate 3", Percentage.Type}, {"Profit 3", Currency.Type}})
in
    #"Changed Type"