let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("dZPPTuMwEMZfJYrEzTKeicceXzlwWECCRas9VD2ENIcIaFCTLqivw5vwZDuJk9TdLVKkyPPF85s/X1ar/HZftYdyU+cqLzSYC3l/fQJYRQE1OTkaTWPYJbJXAZ0OXo6gcQwDHnUcrpP2QY54ka/VKn98bw6H+qXLbvuNREmb+WNDypogkIQFiQ6iW446TGFMdBSd/awP9wfeXfWn6Zu6yy6zH2XVPnXDrSn71yezV+SkAx6hsQO7yMFYxUy6iP0jDeGwIIMtFBNoD6NcTMjf5ctzveuyXzfjMOevffAKjLA5SQZm0SWTQm+1SxtMBsAcVHCsQ9Q9RdrDvhTaaSogo8AV0k86S0x0VBwKbe15FJBTgVlzROGEurnPHrdl9SzLa16bvj5dYOGd1I9S2PkFWkDpnyXbsiAZz7Fo60ixg7jAOLYBet1+dNlV01X7po/Lmy8gWeUNacQTdy6ys8pJk84lvGRIMmvleHDrYomBd7Xf9e22y67bdjOZNBmc1GjAaXceCR5GD/I3SPDyw1D4F/mzfWq23QC9zO7rt67J7sqPZDNSa2FVAX7x6eid42hRjEjBz9b4z1pIpEB0PuUK663ela+NRL97Yu/r9V8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Manufacturer = _t, #"Growth Scale 1" = _t, #"Trigger Point 1" = _t, #"Rebate 1" = _t, #"Growth Scale 2" = _t, #"Trigger Point 2" = _t, #"Rebate 2" = _t, #"Growth Scale 3" = _t, #"Trigger Point 3" = _t, #"Rebate 3" = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Manufacturer", type text}, {"Growth Scale 1", Percentage.Type}, {"Trigger Point 1", Currency.Type}, {"Rebate 1", Percentage.Type}, {"Growth Scale 2", Percentage.Type}, {"Trigger Point 2", Currency.Type}, {"Rebate 2", Percentage.Type}, {"Growth Scale 3", Percentage.Type}, {"Trigger Point 3", Currency.Type}, {"Rebate 3", Percentage.Type}})
in
    #"Changed Type"