let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("ZVTLbhsxDPwVwWciEakHpWsL9JAHkNZoe3Bz2DgLdJHYa2TXbeDf6Z/0y6p0RSVSToaJ2eFwONRms1r/Hk6n/nFSV/P9Clb6TLv0o/7+QUsQnFZLUaqMdqmgwJwH61yGSZXAWF5qJEDWoL3wSdUCOVKrW9isPh+7h/5pIc+f+AjG2UZCEGYkYSawxoiEXASm/KXAggUuA70qZcZFwLdhN481i0UIHERAGUXLvJk6WUWRGp2EmCumoFizoDjDDOml/ZfxbthP435S5+qmP0yDuu6eKzVEGmJ8J8c5qhsROTBs204IPsr4PiMNQjSx8cSA5biI+jQ+/zimVjypD8enedzLv4/j7tDth36qjXAE+C40yR0vXtgM9AipX+M2eGwE2hSBELARyKBtWAReHbfjqbvvswGyfTYpWNgmx3thL7iQNleiQ6IXreiIggwGjLH13g14z4uO6+2vYU52pOVddNvxTnzJraOnZHQxRiKZ0hXr3UXP4InbHb8cVEEKZ8q9IfGwLB8CZm++d4/poib19fLtVfnAYF6tL+kg0BTq42YM4BzXQ6NN4cLqtNhG4BJMKnfi03w53Rdjr/5nx6t1f/iZY1QTpyw6UzejYrktMjGENkyxTk0CWaK6xtosSi5v1HrfbR/Skzfshrmvn720YyBs35x0OjJydtE4DUixDrABp7G20HifwmqbADuw8eXVuf0H", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Manufacturer = _t, #"Growth Scale 1" = _t, #" Trigger Point " = _t, #"Rebate 1" = _t, #"Profit 1" = _t, #"Growth Scale 2" = _t, #"Trigger Point 2" = _t, #"Rebate 2" = _t, #"Profit 2" = _t, #"Growth Scale 3" = _t, #"Trigger Point 3" = _t, #"Rebate 3" = _t, #"Profit 3" = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Manufacturer", type text}, {"Growth Scale 1", type number}, {" Trigger Point ", Currency.Type}, {"Rebate 1", type number}, {"Profit 1", Currency.Type}, {"Growth Scale 2", type number}, {"Trigger Point 2", Currency.Type}, {"Rebate 2", type number}, {"Profit 2", Currency.Type}, {"Growth Scale 3", type number}, {"Trigger Point 3", Currency.Type}, {"Rebate 3", type number}, {"Profit 3", Currency.Type}})
in
    #"Changed Type"