let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("fVXbahtBDP2VxdC3YSpppLm8NlBoLpA2tH1I87Bx9mFJbAdf2pDf6Z/0y6q9ZHd2CgWDsaQZnTnnSL69XV2e1rvX+qFZmZWzCO/0u/rzGzkagGgdVRoAK2+JwGCBu6DPqoVMcGhjn0BLU8JERzbEPkzZAe8MsljuD7gxyiYmts5Xqztzu7r51b6+Nk+H6vL4oHmxMLcTg3qddyW4IFZ83ywvD844jxYHGHM5GQ9guX8i5QeSNxy8BvrMfIBNQrQJBoBX65/tsW0O1fvqvF7v7g/L4hTBeHYW4oAyIyUpGkpdmOd6VMLRYASlaTjBc18AtqEHmjKcBkR7RA3h8LQ5BUbA25gGqN/rp8dmf6i+XvQYp7IYlEnhCWP2UqdchlAtmU+gQietc0W/ZICCTQMMyOLqjMSTKjbI5ADjlWKRAeDnU60Ai8OY9HUQRv9k6JK40YS5zqT0RYJRNmVYJp2F1IXSq5ndT8iGnRszmTGcIVRsOGC7uK5utvX6UZ3YbtpjU7iRSZ9CbAkLlGRQL0cqcaq1TNTA4ICsbVAtyJIr/SgMxinrPhR+RKcqp16mDujH3cuPE6gQh+rDaX/cbd9+ne02z/VWrbpUn7vzoiqWQ04GvNLuhzGf6536k6NNXADXcdH6AXguIKs9nU4MYgkcDckgbAf8y+6+3R52226UrpvnQ1td1S9Lg5FuDPbKwcjyJK6XaL0UPqXA+jJnfSysoJfonkpUIqWYTNSB+YfiYEjtiyPDCu652debVpP/+XSN9OUi0wqZGnV+xnGBXDTH41NTIE9qAqVYCkm6bRlSaSWn1tbxZywE4RjHZeyyR7pkJJCNva4u3yMYFdW4K761m+NuSb7TPwOVEVzBfZIxJosm3ZKUknlOsV9HhUN0SOgtQYtlqPIRDZDOTw+6Zj+tm+ps39Sb4g41GcA89ll8CubLHXBRnrUUnATLt5AsD4R5rXjuICvGu78=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Manufacturer = _t, #"Growth Scale 1" = _t, #"Trigger Point 1" = _t, #"Rebate 1" = _t, #"Profit 1" = _t, #"Growth Scale 2" = _t, #"Trigger Point 2" = _t, #"Rebate 2" = _t, #"Profit 2" = _t, #"Growth Scale 3" = _t, #"Trigger Point 3" = _t, #"Rebate 3" = _t, #"Profit 3" = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Manufacturer", type text}, {"Growth Scale 1", Percentage.Type}, {"Trigger Point 1", Currency.Type}, {"Rebate 1", Percentage.Type}, {"Profit 1", Currency.Type}, {"Growth Scale 2", Percentage.Type}, {"Trigger Point 2", Currency.Type}, {"Rebate 2", Percentage.Type}, {"Profit 2", Currency.Type}, {"Growth Scale 3", Percentage.Type}, {"Trigger Point 3", Currency.Type}, {"Rebate 3", Percentage.Type}, {"Profit 3", Currency.Type}})
in
    #"Changed Type"