let
    Source = Excel.Workbook(File.Contents("\\rivsts01\SHARE\Finance\Finance Secure\MIS\MIS Main Final.xlsx"), null, true),
    Sheet1_Sheet = Table.PromoteHeaders(Source{[Item="Sheet1",Kind="Sheet"]}[Data], [PromoteAllScalars=true]),
    Types = Table.RemoveColumns(Table.TransformColumnTypes(Sheet1_Sheet,{
            {"Inv Month", type text}, 
            {"Inv Year", type text}, 
            {"Inv Date", type date}, 
            {"Customer Name", type text}, 
            {"Terr Code", type text}, 
            {"Account Number", type text}, 
            {"Order Ref", type nullable text}, 
            {"Trans Type", type nullable text}, 
            {"Inv. No.", type nullable text}, 
            {"Inv Val", type nullable number}, 
            {"Currency Code", type nullable number}, 
            {"Currency Value", type nullable text}, 
            {"Exchange Rate", type nullable number}, 
            {"Amb Val", type nullable number}, 
            {"Frz Val", type nullable number}, 
            {"Chill Val", type nullable number}, 
            {"Spec Val", type nullable number}, 
            {"Foodservice Value", type nullable Int64.Type}, 
            {"Waitrose Ambient", type nullable Int64.Type}, 
            {"Waitrose Frozen", type nullable Int64.Type}, 
            {"Suma Ambient Value", type nullable number}, 
            {"Waitrose Chilled", type nullable text}, 
            {"New Range Value2", type nullable text}, 
            {"Other Value", type nullable Int64.Type}, 
            {"Freight Value", type nullable number}, 
            {"Bibby Val", type nullable number}, 
            {"Services Value (B)", type nullable Int64.Type}, 
            {"Reprocessing Warehouse Value", type nullable number}, 
            {"Handling and Packing  Value (C)", type nullable number}, 
            {"Documentation Value (D)", type nullable Int64.Type}, 
            {"Other Val", type nullable number}, 
            {"Commercial Decisions", type nullable number}, 
            {"Retro Val", type nullable number}, 
            {"Inv Cost", type nullable number}, 
            {"Amb Cost", type nullable number}, 
            {"Frz Cost", type nullable number}, 
            {"Chill Cost", type nullable number}, 
            {"Spec Cost", type nullable number}, 
            {"Foodservice Cost", type nullable Int64.Type}, 
            {"Waitrose Ambient Cost", type nullable Int64.Type}, 
            {"Waitrose Frozen Cost", type nullable Int64.Type}, 
            {"Suma Ambient Cost", type nullable number}, 
            {"Waitrose Chilled Cost", type nullable text}, 
            {"New Range Cost2", type nullable text}, 
            {"Other Cost (Cards / Books / Other)", type nullable Int64.Type}, 
            {"Freight Cost", type nullable number}, 
            {"Bibby Cost", type nullable number}, 
            {"Services", type nullable number}, 
            {"Reprocessing Warehouse Cost", type nullable number}, 
            {"Handling and Packing  Cost (C)", type nullable number}, 
            {"Documentation Cost (D)", type nullable number}, 
            {"Other Cost", type nullable number}, 
            {"Commercial Decision Cost", type nullable Int64.Type}, 
            {"Retro Cost", type nullable Int64.Type}, 
            {"Terr Manager", type nullable text}, 
            {"Z A/C Ref", type nullable text}, 
            {"Case Qty", type nullable Int64.Type}, 
            {"Country  Code", type nullable text}, 
            {"New Territory Code", type nullable text}, 
            {"New TM", type nullable text}, 
            {"Country", type nullable text}, 
            {"Customer", type nullable text}, 
            {"Territory", type nullable text}, 
            {"Region", type nullable text}, 
            {"Reporting Territory", type nullable text}, 
            {"Retro", type nullable number}, 
            {" Total GP", type nullable number}, 
            {"Total GP %", type nullable any}, 
            {"Account number", type nullable text}, 
            {"Classification", type nullable text}, 
            {"Industry", type nullable text}, 
            {"CSEA", type nullable text}, 
            {"MONTH", type nullable text}, 
            {"Type", type nullable text}, 
            {"EU / INTL", type nullable text} 
        }), {"-1", "Account number"}),
    fixspace = Table.RenameColumns(Types, {" Total GP", "Total GP"}),
    FixEULookup = Table.ReplaceErrorValues(Types, {{"EU / INTL", ""}}),
    FixCustomerLookup = Table.ReplaceErrorValues(FixEULookup, {{"Customer", ""}}),
    FixReportingTerritoryLookup = Table.ReplaceErrorValues(FixCustomerLookup, {{"Reporting Territory", ""}}),
    FixGP = Table.ReplaceErrorValues(FixReportingTerritoryLookup, {{"Total GP %", 0}}),
    FixRetro = Table.ReplaceErrorValues(FixGP, {{"Retro", 0}})
in
    FixRetro