let
    Source = Odbc.Query("dsn=Exportmaster", "SELECT 'Order' as ""State"",OrderH.REF as ""Reference"", OrderH.SEQTYPE as ""Sequence Type"", OrderH.CUSTCODE as ""Account"", OrderH.COMPANY as ""Company Name"", OrderH.CONSCODE as ""WH Account"", OrderH.VALNETBASE ""Value"", OrderH.TOTCOST as ""Cost"", OrderH.UF_CSA as ""CSEA"", OrderH.UF_ACCHAND as ""IBM"", OrderH.TERR as ""Territory"", OrderH.UF_LOADTYPE as ""Load Type"", OrderH.UF_RQKEYDATE as ""Release Date"", OrderH.OHSPLPRICEPOINT as ""Price Date"", OrderH.PAY4 as ""Credit Days"", OrderH.INPUTDATE#(lf)FROM NISAINT_CS\OrderH OrderH#(lf)WHERE (OrderH.INSTATUS=1) AND (OrderH.OHINVREF Is Null) AND (OrderH.SEQTYPE In (11,14,41,31,96)) and (OrderH.OHSPLPRICEPOINT In ('2025-11-22', '2025-11-23', '2025-11-24'))#(lf)#(lf)Union#(lf)#(lf)SELECT 'Quote' as ""State"",QUOTEH.REF, QUOTEH.SEQTYPE, QUOTEH.CUSTCODE, QUOTEH.COMPANY, QUOTEH.CONSCODE, QUOTEH.VALNETBASE, QUOTEH.TOTCOST, QUOTEH.UF_CSA, QUOTEH.UF_ACCHAND, QUOTEH.TERR, QUOTEH.UF_LOADTYPE, QUOTEH.UF_RQKEYDATE, QUOTEH.OHSPLPRICEPOINT, QUOTEH.PAY4, QuoteH.INPUTDATE#(lf)FROM NISAINT_CS\QUOTEH QUOTEH#(lf)WHERE (QUOTEH.INSTATUS=1) AND (QUOTEH.QTRESULTORDERREF IS NULL) AND (QUOTEH.SEQTYPE In (11,14,41,31,96)) and (quoteH.OHSPLPRICEPOINT In ('2025-11-22', '2025-11-23', '2025-11-24'))"),
    #"Renamed Columns" = Table.RenameColumns(Source,{{"Value", "Total Revenue"}})
in
    #"Renamed Columns"