let
    Source = Odbc.Query("dsn=Exportmaster", "SELECT 'Order' as ""State"", OrderH.REF as ""Reference"", OrderI.PRODUCT, OrderI.DESC1, OrderI.QUANTITY, OrderI.CUNIT, OrderI.PRICE as ""Case_Price"", OrderI.COST, OrderI.TOTNET as ""Line_Value"", OrderH.UF_ACCHAND as ""IBM"", OrderH.UF_EXPREPRODATE, OrderH.CONS1, OrderH.CONS2, OrderH.CONS3, OrderH.CONS4 #(lf)FROM NISAINT_CS\OrderH OrderH#(lf)LEFT JOIN OrderI ON OrderI.REF = OrderH.REF#(lf)WHERE (OrderH.INSTATUS=1) AND (OrderH.OHINVREF Is Null) AND (OrderH.SEQTYPE In (11,14,41,31,96)) and (OrderH.OHSPLPRICEPOINT In ('2025-11-22', '2025-11-23', '2025-11-24'))#(lf)#(lf)Union#(lf)#(lf)SELECT 'Quote' as ""State"", QUOTEH.REF, QuoteI.PRODUCT, QuoteI.DESC1, QuoteI.QUANTITY, QuoteI.CUNIT, QuoteI.PRICE as ""Case_Price"", QuoteI.COST, QuoteI.TOTNET as ""Line_Value"",  QuoteH.UF_ACCHAND as ""IBM"", QuoteH.UF_EXPREPRODATE, QuoteH.CONS1, QuoteH.CONS2, QuoteH.CONS3, QuoteH.CONS4#(lf)#(lf)#(lf)#(lf)FROM NISAINT_CS\QUOTEH QUOTEH#(lf)LEFT JOIN QuoteI ON QuoteI.REF = QuoteH.REF#(lf)WHERE (QUOTEH.INSTATUS=1) AND (QUOTEH.QTRESULTORDERREF IS NULL) AND (QUOTEH.SEQTYPE In (11,14,41,31,96)) and (quoteH.OHSPLPRICEPOINT In ('2025-11-22', '2025-11-23', '2025-11-24'))#(lf)"),
    #"Filtered Rows" = Table.SelectRows(Source, each true),
    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"Case_Price", "Case_Sell_Price"}, {"COST", "CASE_COST"}, {"Line_Value", "TOTAL_LINE_REVENUE"}})
in
    #"Renamed Columns"