let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jVtZcuNIkr1KWH5JbSUUAIJYPkESIplck6CkzuppswmSkBglEFADhLKkG8xNui8wF8iLzfPAFqBUY/VRykzBI+Dhy/PnHqh//OPL18ktm4uTOEeHL798sS2zZ3uaZeHvX/75yz++3Kb7KNmntYiG3/etnm55mmnUMkN+etlFcfxfha6bTs4GmTiL/Mhu0/SQs2myp1WW3rcNS+t79aplmp14zPxfQxbc4Zc92zL0vmY3u6bxgYXnNONPEQuLlwji2XN0ztmV4bm9a7Y+R5A1Ld11Pc3u1+u2WZQc9lCHhYeEDY4HdtW3LN1ybrbX2GfHkyf2lb9xWmtAK7N95fYYNcqHx/SF3UdZzpPDEf9Fcamm4ei60dcct1402UxwxnOUJfws0gRHCv54STPoOT+TSQ3bcHuWpjfmWmPjuXi8OFQl3O95dk+x0kIc2DBNziKJkjP2np7k3iRq2bqla/3m4Gt/M0vCyWrNfDYSryKHNix9ZO3vryaza1ppOqbV05zG0hPN19iav3BYTSQ8ZwG9RTwL0oqZtMRwLcfVnOYQM5E9qweo9Td6/V5fa8JnnBbZCU9HIj9nYleQhXCe0wtP3pSwMwzT0y3F9/5Q6pOc00SkBdtm/CDgt/olhms3FhoF8+l9sPnOJsFmxcLtahOEbDRgc22uDaW0ju01t1F99QqvRjhlZUsWztkNG0SJyHN+9cCz6JgWeSQtpbuObiruoAipT92cWbd7pq05jT3HGX9jC75/jpJ3EbFNdOYixkPP9foI8F4th+h6fk6fefHywrV9emKrt9/LIPNch6zdxNh44y9H01UYsPBuHWwW8GiwbU7o2S4istk25Cfak00eKe+8vmO4mv5pjI+il/QsZSzX1lyzCbo0e+LJzYNAOPBTfhHeSGgIupZBgdq6TJzf2OStDQh4+RRle8Hp6I5he6Zmuh1pacjKiHgMG5rNISb8QKhTPnPtfk8zmleF89WW3cIkIZOQY7PhSmMD7Z5k+y5Cu9/sQ0eVqTw+7SYS4Dwkjdc8X0CNBK5iA16Hl21ZfV3rNXk1EXQoHIUfUjYdMgCXRJ6+1+uZWq9j2YU8+0vM95ES3tDJ7mtms+MmOiza+OkDHmwFTrcpIn1C4a7mVzhassFkJPHXc+Atp/XWkZ+iA1sU+Zk/8tomCIO8OCBt4AltvQ3qt1mW62iNKv5LGiPHePWu8pRICUIEGYpAe6Onuc2CuUhIoDzof+fqKQEqPSXS1pk4RWycoYJklzFU6aI7lt0ahdKk2phO/xDFuyjKKzV029E1twmg7e26Sqwa5qnGeH3dUGLSB3JnvEGPYZoh4aUKJOw4lqX1GrNP97DDni1wPvVUEOs5mtcgwKzYHxNkdfhD8DPM5pf6WQ5wRgmaUALEOksPxZ5yQfulPLIFPHE00/rySTpSvSxzks3nlNiWbbmu5jWH/lq6dsV8uDrjSE4UwTcJ0qTKesgejmkc5TyGxWl933H7ij3C6G1/BMbDqK1NKiwutevZjpo9Qw7Q3kU8uUBgOBqGbkNwnJ7hXfHId6gagD3mhySFem4reDdiW1TS9CUtYgoxX7ICipkGeEa3UzYv9s9vsJx45Wc1iXpuv6+iLAVK3gT7C1gKwOSG+TG7Lc4IjJNcY5lI0dZ5YpenyYdglMbuOY5naLrZnik9/JAMpvZPGZqlqKECOTlxxEX2xm55drqwac+2e3qbcGA0SXSCGbKW9vQ1t1EReTcW5EBZ+KYvIkvPVJhYsA6qFX2XQq2J285ZUHuSA5PooqLHjVxngIe0hdOPb77yd4EEQY6iXgzCYSVlKGi0SOGxTPwBorb91Yd5BRsAU/AnCfd0HdyrsVltqWkeR5JBvRBQ9kwXKWQoL2arHK99mMvCu1hMScggjGzhYMHz/E3yP0TrVTi/u67tqbvI21YQuy2iCNuBJuUFEIyNpddqL1x900JteF2u7Llak00LUSYD2wI+2dZn9S9qHougovKFI0W5XN7XdeXF6xhGT4oT8haoya78XPBrNWB1w7M1o+VCWRQh9i5IEwFJ9C9RuVY3LFNhWQsk1UEg/UApYYdSC53C1FFjL9wj/8juVTZMM8lgyXaV0UzPhKNaDjpM0zg/F4+PzB+UryYJFQ5nP6gMfSclC/xlDwSrKr/pwVVqOT7zDEaKqjBqDUCcztMMt42OtwOwAXo9R3mjmN5TSWzH7QOe7agckRyqsqscYBHFxJiUl9mmrnDar4MqXVEHM2IgZt9DHWujf8tjvuNnNit+cHGWAmYfUdpqIggnm5w3LRckpA31Mc8AiIi2afIa5ecT6LlaNkxQwp5mNfo+QJY9pBl6msqKUNhQWOkWiZiUtSqq/aiyZlpieJajOY3hJ/5gzcZxupMUyzRcx9Ka8z1EYCvR8ZFR1k4iITlhKUYh1pxjHslMOacCR8lioAcX0uAGtWuN72ZRTGStckzlO8PydM1Utkqe0ioKbths8Z1kdIdoYlvvOJsJiqyyxUD2tMTGRDMGYGtkKbPRqH1KHRCstqnpbWkEqual2TbidEKpAs5SUm95jtBEG0TYxEWyqMJd10HeWpgLBiwMNvfTIZqH4Wqx9pff2Xy6mG4D0sxwXdvVjEZ6ub0bAutFBmTckwFvUlgHGr7WCWegWvWVaAqgBlWTyl913SbnlBpOs4iML5eiwVbSJuSv4gD8JyvgfXn0WQMFDulodqPgIEtT9GecQni/lwJG31BozHR34JyK5TeeZ8RPSMaxUVjamF2Ogax4zSo/k2rIJVL3K9+nuwoi5SLLtDSn7T5+RNTvZRE/sQmQg6MqziIEzXOEHvok2OzxLJf18C67zdciFgXSLRJJzPwT1bEdsIJYe9134wiflJq7WdXHEZLB33NxPsdR7e26ZXcuIXPCTzH0bLp9imsStd2+OqQIgdgy8GKxRz3O2V2CbiDPUwpEcorcv99z1N6lw+fqJvNXFqZJxo+wdbmk57XZtRXxO5HFHFEEvVUggdssQy2eyVOcspaYVcMGkrQsB3DblKesSFruG9yxqzUC6Vf01Scue1urZ4LYt+VJPEo3s9XjI4J6wf+QQoatspMgJhZN4Qo1EFs3JeHA33zUtPef/0lk70Are56H7Ruj+OR/9Vw9D1251zjFXy0vuts2+3pOH5DVaDosaEpB85862UwP3aWtkG9xboohzF65yXRBWq2+6qZyzDPk8rHVdxVmPvohpyFPeQXYeG71Na+x7yac1xWvUgIG7WyfEhMOYCgKhkoFy1BlSoqUfSAFJGp4VOcbsJ/zDAVvF9UelSKOh7aybcHRBx7SmFKi3sO2bc1r+3pAzK7A6i/lpMZWkn1SZHH0llcEcoLKmxZZsw9xDreTQF/T7MAT4iZVTXgEox1HqIhIDUVH3QMJahv/6XLhD+/m/shna/+7T7OX0jK655pKndiAi6X7lJysNXMWD6dpWyw5Q6gHTG0TaOg2UR2ljj8dIei/dKJP7zt9xdmhOL3E6DpSeEqV6rme0hLciixHM3dMCfTL6eZdyPz9Pi2Scylvqf1nhfX+4ZWjOzlUZKI0lSz0co3pqOS4QSSK4ZqJViYyUR7tliG/UeSgss2i/IfYP+P3ngeG2tb2EovDc0Z/zLeUS56tu0qJXQTT0fSG/DBdjv31ahOg+gEptsF1vcCAerbCz0QcpweRy1owpkYF7Lh0QwkEUlcX71GwZRAEq83YX06HZWfoOiAOyrxJcrEM6M+bSSjIjK31W+6Y7sGxa2+jhlTjCddB0tkd6N1TTEJw3/arro3Ox2hbx+gAD2eIdEJQABqilqQsB8nZ7PU1PWKj9+jH/r14LisR6ssg3e3ecul8ya9LLSyQnNaqA9Qk2AI9KfiuTOhaW8t0lUI0mtTzyoE/2fjTJbVEJKZ7lqKI/3120X+7umsrbULD/+epLK54bCmzEl9b8OT8DpOAYT4LdCpyrsrr6KJeO7quNNSpyjYriWc8NTOcNskcB1yzBafVKRE/JLlt9JTB4/RckPvmvJM0lhWmRea8nss5JsDXa8dS8S6ikr4DYjV0B839rmCjI9+Jqmd3jJ46rghXo+mYCggsKU/jEG4ZTZzROD8uErSvM7QZIkmIIEsxdJTty4M8j/5A94cs/4VuL9hhxyuWtmp45BeaWRJPa7ygcM1Jio7yasLRekQntpxXxrUdA8Zt6xjEMzgC9QfacAbWwuNDQbUt3FS4aPcMV6m/AxElcOZTlMmBcSliwtstLNaNzTeOvkw+7nudrrU4FSBI4A28Kn8bOb05gLANtHut2hOB2m+bE2VKtY4OcbUxwKZtA4dvyflIE6mMuDD1zBIiqD3KMvGERKM8oHXUFrdH+gpGQu/Pia/ThOEDZa8mgFRI2phHhNBdQjPD/xFRb0kckCh1ENaLTHWAhh5/D/MVpWryPRJBzzjf3UzKoz4rg9oCoRDH3SstaTSSpauBtgPZRHEEnD/DQMkTnFiFaJ+q0Z/M+6gnlDsOUwkt+L02POajSA5XQBHVgcg9gPfiKqweo6IvVJjWuEwvQO0juhO1cSCW2NfB+hRcpYHHq5BjkCp16ws7srehdBRCskyL6nTbR8DbxQGVs3yXnKu6rnqBNZqtNgwJCXKnzSsYRCttKKOGsi0up5+deyK0APmZMr9cZRtq4/pnq6ihzX7+O68X0VSgcSioEU2HKDiv1hGN4q7rsLTogstqR5FpvG8a8bq8pRUXtCxkpdXgGo64DOZTnz34m5F/s14tp8FwVk+G0TxqemMPen0VRuVgwjLQZ/cah3wrXzmjcdYjfIbyWm5DmN5r1Nts2SLN8mPED/VMFrxH0T+EOpsQmq2nq2WVDZaOVq3bQlF+5SVeVTyuHEQReW/ftoUn3nj9CI13q+9aRHuZrDBt9bznKhb/yk+7VA1aKaI7baMy56+A25d4X613bUsJMJkwxXl/jLK6XlF+VLKO7Skp+P1iVHB1N2umhjZCrg0eNQ3rSUQ93wIvBga0N7D8/ApPEbrcR4cDRWQzNOv1TU+BSTnhAx+EGavHhq30LbMoSaLDW6NWtYdFcNjIiBNbAS/zEqK+FSB2iJRXEG78qF2A+NMcBUE3YD1HEbHzryhUx/TEiceTLtOdeK8X9ag7bHVNz9GO8DWRJL4Gzosb8HKlaTgf2i+o2N42KIQMbb2n4AuwnboEedyrEY7QDFfbiLhuVhrK/AqyL+kPuiA88F/YeND06KbsKJqDlMkPaEy7l1htf25SuLWfNMzvQqREBc+m6+lNyogTAAHnL/CTrDFEygPaaKDeUD3TBSorJByVpuwCQ1+uWbzJylrVCEibSv0JAcPJ06OIFKZ0ZXh9r246rtFQyFGYS7DVNlzRKU3j36MGkIb13ajZt9WbiECbaWzsz/2lP5uGbIp/BpoUMx2ld12kOwGv4XxnihLynhTS+0o034tXUAnUshoUTJovtIcBb6Zb9C74lkpZjq7pbXPlh8jZR5Gkr7VHaPrhtQJpgQqcJcrXDaZpq13REBmY5ohzkImU/d2wXde09PtqNxM9jd7aoOq4JbcJefy+K7InNhtXwgYxAuUOPo7eK+j7IkeQrtKYbJCHKdv8/M+TyMm5AXFCIDKbc3b78z8RfSByrgLD8ECJ3ZZnCQKp85HuFMtWUV54GS562HYsuE6p2a6GADQjrMLScA316mAbxTfr6Jlnxc0MeXGzBRI8P5+rF9souLZq7PFmdbeud+qj/DSBtI5epPIwi1KPDat9VciT32mIW0AnggV6TJOCtpmbi+8FivMRj9fragO6Dmwp6ApMgKe1Aqal9jzKVyoig4/EC43Ov8iBh5L+DQf0kc6SxVRTgr6SFgORPUMMXKvqtNtxoYsI7LWUSDJthSxovw6pp0HXRDdZJ4p+B6hvtDefkZy0LlOBxKfRGEWHQ5WtpT6grW9qTSIJFNiWF9wBVQciJWtXB7DRt9ntDRR2qK5ppjVf6QjQl1VF3ia9xm4zGiWghaPpW/X7pThFeQ2iMJD9ly4TIdMgX3OHVk8oQn817Ao0134XNZb6uXbs01lz4u+ABLoWu1nzvXhEJqADPMiZWju8a+QH/tbfIHrbC4H2EX8jrt95MaxxuQEl020W0cBHbZjROA7Xg01HtKpxO4Bu/tmDcihQYkjbv38QC047eWHVfTrkj48//82a/u4gWLjnQCUqL7UzNRYuhx8Wkr8r/q54G8QESUJd+l+R3hyJ13YlK004u0cxHlZFOc/iDwpUgr4UvI35ScivQzRfCy+N0O4q0MNlIkVwhFqmxR8EBbp5tKv34illedx5BDfF9N0MfT/A4/yTu41GdiRrM6Kwnh+c+T4iyddywt2RRaF9rgVl3jcfdiFfnuhll/EXnETGqSEcpu1tTpjuRXR+68rR9X0hYvZblL2mT4IoVCeIAnDEoj3JvJNKtzApGqay74NXJadpn34cMf5ttGLL1RbMIPhbR3QeLKbL8YoFy22wWW+mv4GL3P42XHWE5BarRxYU1Jd/ZtbbTRAOscvfh8SM7jvAcFvEMV02RCyHY9NLx/7JlfY4fU//gti3gh/+glh5Qa4Kys/MmJz/NmneNfJ0L2/TKK7KiWP7JKHPWfHzMS7OCZYWWTUFakXoSxrlW5mLOJlj45w+CUWFTzoPBBxXcDbJRXSs7soQAft6vqgIyjuq++hJfllDU0/1MUA4T2vSMO88SakHrUtiMyRqn2fsgf3Gs11JX4sMgfZAPztCb/UOSX1HfrHLb+SDl1h0oXGtrSH/xN9B5KiKyql35yuDVpRndG8v+HMnDj7jRBfv7tAXZnQe0ZSzuRq7XAeHPB0BRDIqPpklpJc6hmCccYruqtPzfHaa8CWOYHcEyhpBRVFZdxatSLjesPX2ezX3bH9f7I90iXpI37lCuJTnT/wR0Pnh1/GZJtMRVbzuA8St7IpW9Imm2OeyAD8gUJMoVye0yhL1m0wg0w6HoOgh0i11uvvw9nZFVXP3Vc0dfCpaNVyd3S9DcwvYO4maYHSfgL8V8aNya9Q+g29uefwsk3ma0x9/9u1aZ82Ykqo7taukO5K0UbdrDOd35b/DNGbfSd2Lc9zNStSGNdr2t7rN78jBOUj85gumyfP1pchvMtgms89A2R/6gP3wfnwZUfW3o/UHch+ClRcHoXxF+f8YSf1YFX+nufOHyKfz0+ijtH0XpTofaN2PP5xvuFk9LFn47c6X10rL+2A5DZbDgAV+uB37m1Gw7ECzj2Yro9SuR3Sf2GXhwyr+Yj1ZbTprwf3gy6a+XSAHQGX9dT1AKQhXw+nP/wkvnDrhLy+oJcXpdIF5m+iJvvD6DA7RAD3W+Plbdr7MbBpDHnm2B/x0U3jDf39Oy+u/jOKCPoaZ4cf1paep7Ean6vLl4uWVu5qvk9rXDgZsulivNtuQXRbFZfBQ3a2Hq7vNENzhk09d/gqb9terTllabfzJwA+DT7cBj6KRWUXF6n8ONyGbjy7Rv/0wPabXfii9i7v5dsr8MaJoSoOXYBls/DnbbvwRTtMt82qvMBIvcXrCv/aNK6tIUdeU32uU3+FUs0C1AaILigce03dFbZ/5J+kwLt7QAl9f7vLxG4tq3vNncdxJWZwyWG9WbHV7iwYaORX6HTdsJwEbT2+3dIWLWPpAwtVP7qn77qhfoEbtjyhX9bSnVTrNjvR/Acgh8UfGOh5O2CbY+tM5u1r4c/97OPWvqYnT0MRpnfJPH0uVH0ZfnNo/PP783y7yy0l9edt7SaCRFtSYZdXlycXjdbjYNl8OXjpg4X+djhhC5vZuC5UXbPK9+eIk7Oz0z/8D", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Customer = _t, #"2024 Sales" = _t, Column1 = _t]),
    #"Removed Columns1" = Table.RemoveColumns(Source,{"Column1"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns1",{{"Customer", type text}, {"2024 Sales", type number}})
in
    #"Changed Type"