let 
    sql = "SELECT
    SASOURCE, 
    SAPOSTING, 
    SASEQ, 
    SAIGNORE, 
    SAADJUST, 
    SAREF, 
    SADATE, 
    SAINV, 
    SACUST, 
    SATERR, 
    SACLASS, 
    SAINCOTERMS, 
    SASIC, 
    SACREDIT, 
    SASELLCO, 
    SAPRODUCT, 
    SAGROUP, 
    SAEXTRA, 
    SAHAZCODE, 
    SASHIPTYPE, 
    SACOMMOD, 
    SARECIPE, 
    SAANALYSISH, 
    SAANALYSISI, 
    SAFWDR, 
    SAVAL, 
    SAVALORG, 
    SACURR, 
    SAVALGROSS, 
    SAVALNET, 
    SACOST, 
    SACOSTGROSS, 
    SACOSTNET, 
    SAQTY, 
    SAORGQTY, 
    SAWGTNET, 
    SAWGTGROSS, 
    SAWGTSHIP, 
    SAVOL, 
    SAVOLSHIP
FROM
    Analysis
	",
    Analysis_Table = Odbc.Query("DSN=Exportmaster", sql),
    #"Removed Columns" = Table.RemoveColumns(Analysis_Table,{"SASOURCE", "SAPOSTING", "SASEQ", "SAIGNORE", "SAADJUST", "SAEXTRA", "SAHAZCODE", "SARECIPE", "SAANALYSISH", "SAANALYSISI", "SAFWDR"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"SAREF", "RIOrderNumber"}, {"SADATE", "InvoiceDate"}, {"SAINV", "InvoiceNumber"}, {"SACUST", "CustomerNumber"}, {"SATERR", "TerritoryCode"}, {"SACLASS", "CustomerClass"}, {"SAINCOTERMS", "IncoTerms"}, {"SASELLCO", "SellingCompany"}, {"SAPRODUCT", "ProductCode"}, {"SAGROUP", "ProductGrouping"}, {"SASHIPTYPE", "ShipmentMethod"}, {"SACOMMOD", "CommodityCode"}, {"SAVAL", "Revenue"}, {"SAVALORG", "OriginalRevenue"}, {"SACURR", "Currency"}, {"SAVALGROSS", "GrossRevenue"}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns",{"OriginalRevenue", "GrossRevenue", "SAVALNET", "SACOSTGROSS"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"SACOST", "Cost"}, {"SAORGQTY", "QTY"}}),
    #"Removed Columns2" = Table.RemoveColumns(#"Renamed Columns1",{"SACOSTNET", "SAQTY", "SAWGTNET", "SAWGTGROSS"}),
    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns2",{{"SAWGTSHIP", "ShipmentWeight"}, {"SAVOL", "Volume"}, {"SAVOLSHIP", "ShipmentVolume"}})
in
    #"Renamed Columns2"