let
    sql = "SELECT
    REF, 
    SECTION, 
    LINE, 
    LINEID, 
    PRODUCT, 
    EXTRATYPE, 
    EXTRAPERC, 
    EXTRADISC, 
    EXTRASECTION, 
    EXTRASUBTOTAL, 
    DESC1, 
    DESC2, 
    DESC3, 
    DESC4, 
    DESC5, 
    USELONGDESC, 
    LONGDESC, 
    QUANTITY, 
    QUNIT, 
    CUNIT, 
    CUNITFAC, 
    PRICE, 
    PUNIT, 
    PRICEPER, 
    VATCODE, 
    DISCFLAG, 
    DISCRATE, 
    DISCDESC, 
    COMMODITY, 
    PACKNO, 
    EXTRAPACK, 
    COST, 
    COSTPER, 
    PACKCOST, 
    PACKCOSTPER, 
    WGTNET, 
    WGTNETTOT, 
    WGTGROSS, 
    WGTGROSSTOT, 
    WGTPACK, 
    WGTPACKTOT, 
    WGTPER, 
    WGTTOTIND, 
    VOL, 
    VOLTOT, 
    VOLPACK, 
    VOLPACKTOT, 
    VOLPER, 
    VOLTOTIND, 
    TOTNET, 
    TOTGROSS, 
    TOTVAT, 
    DISCVAL, 
    DISCVAT, 
    ORGORDREF, 
    ORGSECTION, 
    ORGLINE, 
    ORGCUSREF, 
    ANALYSISCODE, 
    DUEDATE, 
    ORIGIN, 
    PERTEXT, 
    OINOTC, 
    OIEXTVALUE, 
    OISERVICE, 
    OIORIGINDESC, 
    OIENQUIRY, 
    OIENQLINEID, 
    OIDECLINE, 
    OIPURCQTY, 
    OIQTYALLOC, 
    OIQTYPICK, 
    OIQTYINV, 
    OIQTYDESP, 
    OIORGLINEID, 
    OILOC, 
    OIFROMSTOCK, 
    OIORGQTY, 
    OIPROC1, 
    OIPROC2, 
    OIORGPRODUCT, 
    OICHGREASON, 
    OIREVCHRGSERVICE, 
    OIBOM, 
    UF_DATECHECK, 
    UF_ITEMTEXT, 
    UF_REASON, 
    UF_EXPIRYDATE, 
    UF_PRODDATE, 
    UF_2NDWHTXT, 
    UF_ORIGQTY, 
    UF_ORIGCOST, 
    UF_ADDTYPE, 
    UF_LOCKPRICE, 
    UF_WEBEXPIRY, 
    UF_BANOVERRIDE
FROM
    ORDERI;",
ORDERI_Table = Odbc.Query("DSN=Exportmaster", sql),
    #"Renamed Columns" = Table.RenameColumns(ORDERI_Table,{{"REF", "RIORderNumber"}}),
    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"EXTRASUBTOTAL"})
in
    #"Removed Columns"