let
    Source = Odbc.DataSource("dsn=Exportmaster", [HierarchicalNavigation=true]),
    NISAINT_CS_Database = Source{[Name="NISAINT_CS",Kind="Database"]}[Data],
    CUSTOMER_Table = NISAINT_CS_Database{[Name="CUSTOMER",Kind="Table"]}[Data],
    #"Renamed Columns" = Table.RenameColumns(CUSTOMER_Table,{{"CODE", "Customer Code"}, {"CPYNAME", "Customer Name"}}),
    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"ADDR1", "ADDR2", "ADDR3", "ADDR4", "CONSCODE", "PAY1", "PAY2", "PAY3", "PAY4", "INCOTERMS", "SALES1", "SALES2", "CONTACT", "PHONE", "FAX", "EMAIL", "EDI", "SELLCO"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"TERR", "Territory Code"}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns1",{"ORDTYP", "SEQTYP", "SLACC", "EVCUSTOMER", "EVREGST", "EVVATNO", "EVDESTST", "EVTERMS", "EVTRANTYPE", "EVMODE", "EVIND", "CUSCLASS", "SICCODE", "CURR", "NOTES", "CUSTOMER", "PROSPECT", "VATANAL", "ANALYSISCODE", "PROFILE", "CUEVDECLSSD", "CUEVDECLESL", "CUUSER01", "CUUSER02", "CUUSER03", "CUUSER04", "CUUSER05", "CUUSER06", "CUUSER07", "CUUSER08", "CUUSER09", "CUUSER10", "CUALTINVCURR", "CUCOSTMODEL", "CUENQMARKUP", "CUOTHADD1", "CUOTHADD2", "CUOTHADD3", "CUOTHADD4", "CUOTHADD5", "CUMOBILE", "CUWWW", "CUCTRYCODE", "CUOTHCTRYCODE", "CUALERT", "CUALERTTEXT", "CUEVREVCHRG", "UF_CONSIGNE", "UF_FINALADD", "UF_PROMQTYLVL", "UF_EXPPROOF", "UF_LABTEXT1", "UF_LABTEXT2", "UF_ROUTING", "UF_AREA", "UF_FREIGHT1", "UF_FREIGHT2", "UF_COLLECT1", "UF_FCOLLCNTRCDE", "UF_INTADD1", "UF_FDELYCNTRCDE", "UF_DELTELNO", "UF_DELCONTACT", "UF_SUCCCARR", "UF_FRTADINF", "UF_FRTTERMS", "UF_WH_INSTR", "UF_PLLLABEL", "UF_XCONSOL", "UF_XSECURITY", "UF_BLACKWRAP", "UF_CORNERS", "UF_CROSSDOCK", "UF_THERMALWRAP", "UF_PLLHTREST", "UF_SAADDOCS", "UF_VGM", "UF_TYGARD", "UF_STINVDEC", "UF_INGLABELS?", "UF_INGLBLLANG", "UF_INGLBLLANG2", "UF_LABTEMP", "UF_ALTPROF1", "UF_ALTPROF2", "UF_ALTPROF3", "UF_ALTPROF4", "UF_ALTPROF5", "UF_ALTPROF6", "UF_ALTPROF7", "UF_ALTPROF8", "UF_ALTPROF9", "UF_ALTPROF10", "UF_ALTPROF11", "UF_STOP", "UF_STOPUSER", "UF_STOPDATE", "UF_DD", "UF_CR_AVAIL", "UF_CR_OVR_EXP"}),
    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns1",{{"UF_ACCHAND", "Sales Person"}, {"UF_CSA", "CSA"}})
in
    #"Renamed Columns2"